---
- name: change oracle user password
  hosts: all
  tasks:
  - name: copy sql script to hosts
    copy: 
      src: /home/oracle/software/changepwd.sql 
      dest: /tmp/changepwd.sql
  #- name: change passwd
    #shell: sqlplus / as sysdba @/tmp/changepwd.sql    
    
