---

- name: Update Oracle DB User Password
  hosts: all
  tasks:
  - name: Update Oracle DB User Password
    oracle_user:
      #optional default value shown
      #hostname: localhost
      #optional default value shown
      #port: 1521
      user: testuser
      password: R3dh4t11
      #must be sysdba to change passwords
      mode: sysdba
      #service_name == database_name
      service_name: XE
      #schema == DB user
      schema: XE
      #schema_password == DB user password
      schema_password: R3dh4t123
      update_password: always
      state: present
