---

- name: Update Oracle DB User Password
  hosts: all
  tasks:
  - name: Update Oracle DB User Password
    oracle_user:
      #optional default value shown
      #hostname: localhost
      #optional default value shown
      #port: 1521
      user: "{{ oracle_dba_username }}"
      password: "{{oracle_dba_password }}"
      #must be sysdba to change passwords
      mode: sysdba
      #service_name == database_name
      #service_name: "{{ oracle_service_name }}"
      #schema == DB user
      #schema: "{{ oracle_schema_name }}"
      #schema_password == DB user password
      schema_password: "{{ oracle_schema_password }}"
      update_password: always
      state: present
